services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kid_me_web_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app  # Mount src directory for live reloading
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env # Load environment variables from .env file
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: kid_me_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    ports:
      - "5432:5432" # Expose PostgreSQL port for client access
    env_file:
      - ./src/.env # Load database credentials from .env file
    restart: unless-stopped

volumes:
  postgres_data_dev: