services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kid_me_web_prod
    command: gunicorn workspace.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles 
      - media_volume:/app/mediafiles    
    expose:
      - 8000
    env_file:
      - ./src/.env.prod 
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: kid_me_db_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    ports:
      - "5433:5432" 
    env_file:
      - ./src/.env.prod 
    restart: unless-stopped

volumes:
  postgres_data_prod:
  static_volume:
  media_volume: